# Generated by Django 4.0.4 on 2022-05-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='date_od_birth',
            field=models.DateField(null=True),
        ),
    ]
